# This file contains the information needed for Shopify to authenticate
# requests and edit/update your remote theme files.
#
# 1. Set up a private app (https://help.shopify.com/api/guides/api-credentials#generate-private-app-credentials)
#    with "Read and write" permissions for "Theme templates and theme assets".
# 2. Replace the required variables for each environment below.
#
# password, theme_id, and store variables are required.
#
# For more information on this config file:
#   Configuration variables | http://shopify.github.io/themekit/configuration/
#   Ignore patterns | http://shopify.github.io/themekit/ignores/

---

development:
  password: 04487256d842a6f15e7b93384becbd5a
  theme_id: "178061906"
  store: airplantman.myshopify.com
  ignore_files:
    - settings_data.json # Uncomment this line to avoid resetting theme settings
    - src/assets/min/*
    - src/assets/.sass-cache
    - src/styles/*
    - todo.org
    - ./README.md
    - ./config.codekit

production:
  password: 04487256d842a6f15e7b93384becbd5a
  theme_id: "8576440"
  store: airplantman.myshopify.com
  ignore_files:
    - settings_data.json # Uncomment this line to avoid resetting theme settings
    - src/assets/min/*
    - src/assets/.sass-cache
    - src/styles/*
    - todo.org
    - ./README.md
    - ./config.codekit
